version: "3.8"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 9117:9117 # Jackett
      - 7878:7878 # Radarr
      - 8989:8989 # Sonarr
      - 8080:8080 # qBittorrent
    volumes:
      - /mnt/cloud/dockerData/portainer-created-container-data/gluetun-config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - SERVER_CATEGORIES=${SERVER_CATEGORIES}
      - TZ=${TZ}
    restart: always
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett-stack
    network_mode: service:gluetun
    volumes:
      - /mnt/cloud/dockerData/portainer-created-container-data/jackett-config:/config
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    healthcheck:
      test: curl -sf https://example.com || exit 1
      interval: 1m
      timeout: 10s
      retries: 1
  radarr:
    image: linuxserver/radarr:latest
    container_name: movies-radarr-stack
    network_mode: service:gluetun
    volumes:
      - /mnt/cloud/dockerData/portainer-created-container-data/radarr-config:/config
      - /mnt/cloud/automatedMedia/:/data
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    healthcheck:
      test: curl -sf https://example.com || exit 1
      interval: 1m
      timeout: 10s
      retries: 1
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: tv-sonarr-stack
    network_mode: service:gluetun
    volumes:
      - /mnt/cloud/dockerData/portainer-created-container-data/sonarr-config:/config
      - /mnt/cloud/automatedMedia/:/data
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    healthcheck:
      test: curl -sf https://example.com || exit 1
      interval: 1m
      timeout: 10s
      retries: 1
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent-stack
    network_mode: service:gluetun
    volumes:
      - //mnt/cloud/dockerData/portainer-created-container-data/qbittorrent-config:/config
      - /mnt/cloud/automatedMedia/downloads:/data/downloads
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    healthcheck:
      test: curl -sf https://example.com || exit 1
      interval: 1m
      timeout: 10s
      retries: 1
networks: {}
